before_script:
  - sudo apt-get install -y texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-lang-hungarian
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ utopic universe multiverse"
  - sudo apt-get update
  - sudo apt-get install -y pandoc pandoc-citeproc

script:
  - make html
  - make epub
  - make pdf
